+) A little testing framework was implemented which produces this kind of output:
    --- tests.c:21 (main) - a test suite started ---
    --- ut_clock.c:239 (ut_clock_tests) - a test suite started ---
    Error: ut_clock.c:172 (test_clock_drawPattern_correct) - [-48] pattern CLOCK_ALPHABET[CLOCK_1] doesn't match the screen
     ----> test_ut/test_ut.c:21 (_runTestSuite) - [-48]

    --- ut_clock.c:239 (ut_clock_tests) - a test suite completed --- 4 test(s) ran. 3 succeded, 1 failed
     ----> test_ut/test_ut.c:21 (_runTestSuite) - [1]

    --- tests.c:21 (main) - a test suite completed --- 1 test(s) ran. 0 succeded, 1 failed

+) The following tests were implemented:

    TestUnit testSuite[] = {
        { test_clock_slidePattern_returnsCorrectResult, "test_clock_slidePattern_returnsCorrectResult", FALSE },
        { test_clock_drawPattern_correct, "test_clock_drawPattern_correct", FALSE },
        { test_clock_displayBinaryNumber_correct, "test_clock_displayBinaryNumber_correct", FALSE },
        { test_clock_slideText_correct, "test_clock_slideText_correct", FALSE },
    };

*) lib/clock.c::clock_displayBinaryNumber() was rewritten to unset
pixels which should be off. It was setting only those which should be on
before.

+) include/Makefile.include now has $(POST_INCLUDE) which is appended to
$(INC). May be usefull in child Makefiles